### ISSUE TITLE
Backwards Compatibility Test - Check the website in old browsers with Docker

### ISSUE THREAD

**Issue by jayc13** [AngularMVD/angularmvd#10]
Sería utópico pensar que todos los usuarios tienen las versiones más recientes de los navegadores. Ante ese problema, nuestra web tiene que funcionar tanto en las nuevas como en versiones anteriores de numerosos navegadores. Mi solución con Docker ayuda a evitar los dolores de cabeza que esto trae.

* Javier Hernán Caballero García
* [Github](https://github.com/caballerojavier13)
* [Website](https://www.javiercaballero.info/)

**Comment by matiasdelgado** [comment]
LInks a las [Slides](https://docs.google.com/presentation/d/1WXyUaR-TLqULRdSGrkpoy21UzdgaV3GhcKpTxZugF4g/edit?usp=sharing) y [Repo](https://github.com/caballerojavier13/e2e_backward-compatibility-test)
