### ISSUE TITLE
Angular Elements

### ISSUE THREAD

**Issue by brunob15** [AngularMVD/angularmvd#13]
* Bruno Bradach

¿Qué son y que ventajas tienen los Web Components? ¿Como generarlos con Angular?. Uso de componentes Angular dentro de otros frameworks. Aplicación en plataforma CMS.

**Comment by gquinteros93** [comment]
Cierro ticket porque la charla fue dada en la meetup de Agosto de 2020.
[Link de la meetup](https://www.youtube.com/watch?v=Hgoq8sxBGSc)
