### ISSUE TITLE
Custom and reusable FormControls

### ISSUE THREAD

**Issue by joaqcid** [AngularMVD/angularmvd#15]
* Joaquin Cid
Trabajar con forms y formcontrols es muy habitual cuando desarrollamos web apps. En la charla vamos a ver algunos de los problemas mas comunes que tenemos cuando creamos controles (duplicacion, validacion o implementar logica custom) y algunas tecnicas para poder resolverlos.
Vamos a conocer la interfaz ControlValueAccessor y como podemos aislar un control para poder reutilizarlo en cualquier lugar en una app. Finalmente vamos a ver como crear un modulo con todos nuestros componentes.

* [Twitter](@joaqcid)
* [Github](@joaqcid)

**Comment by matiasdelgado** [comment]
https://github.com/joaqcid/custom-form-controls

https://docs.google.com/presentation/d/1dEJT5hwHn2zrTU2HxpDjsTT1DlyFxytghjjvbswn8hA/edit?usp=sharing
