### ISSUE TITLE
Building angular apps with ngrx

### ISSUE THREAD

**Issue by salimchemes** [AngularMVD/angularmvd#17]
* Salim Chemes
* En proyectos complejos es necesario definir una estrategia para manipular el estado de nuestra app. Vamos a revisar que es ngrx, como nos ayuda a hacer nuestras implementaciones mas sencillas (y resolver bugs más rapido). También vamos a repasar cuando NO es conveniente una solución de este tipo. Vamos a charlar tanto de cuestiones puramente técnicas como de experiencias y situaciones a las que nos enfrentamos.
* [Twitter](https://twitter.com/salimchemes)
* [Github](https://github.com/salimchemes)

**Comment by matiasdelgado** [comment]
https://docs.google.com/presentation/d/10yUCaUrxRX_gZRm7Y5cfnBbzw0f3ovGVRbznXjNsb4g/edit
