### ISSUE TITLE
Ionic

### ISSUE THREAD

**Issue by gquinteros93** [AngularMVD/angularmvd#31]
El objetivo de estas charlas es presentar Ionic, como se pueden hacer aplicaciones moviles con este framework y cual es la relacion de Angular con Ionic.

* Tu nombre
* [Twitter]()
* [Github]()
* [Website]()

**Comment by eduardoRoth** [comment]
Eduardo Roth
twitter: [@eduardoRoth](https://twitter.com/eduardoRoth)
github: [@eduardoRoth](https://github.com/eduardoRoth)
https://eduardoroth.mx (en construcción 😅)

Llevo trabajando con Ionic desde su versión 1 hasta la actual, y varias aplicaciones disponibles en App Store.

**Comment by gquinteros93** [comment]
@eduardoRoth ¿cómo andas?
Se nos cayo un orador para nuestra próxima meetup (este miercoles 19 de Agosto).
¿Te gustaria dar tu charla de Ionic en dicha meetup?

**Comment by eduardoRoth** [comment]
@gquinteros93 Hola, en qué horario sería?

**Comment by gquinteros93** [comment]
@eduardoRoth Seria a las 19 hrs de Uruguay (UTC-3).
Podes disponer de 30-35 minutos para tu charla

**Comment by eduardoRoth** [comment]
@gquinteros93 , ok, ahorita te confirmo para terminar de revisar mi agenda. ¿Es algún punto en específico de Ionic, ya tenían un tema visto, o es una demo sobre qué es y para qué sirve Ionic?

**Comment by gquinteros93** [comment]
Genial @eduardoRoth , gracias por tu pronta respuesta.
Estaria bueno orientar la charla a:

- ¿Qué es Ionic?
- ¿Para que sirve?
- ¿Cómo relacionarlo con Angular? 
- hacer una demo

¿Qué te parece?

**Comment by eduardoRoth** [comment]
@gquinteros93 Ok, va, me parece bien. Ya revisé y me queda bien a las 7:00pm UTC-3 (5:00pm México UTC-5).

Los temas también me suenan bien. ¿Hay alguna presentación base o diseño una? ¿Qué nivel tienen los participantes en relación con Angular?

**Comment by gquinteros93** [comment]
@eduardoRoth excelente, te esperamos.
No, no tenemos una diapositiva base, lo dejamos a gusto del orador.
Lo que si te copio son los links de las últimas meetups asi puedes ver el formato:
- [Julio](https://www.youtube.com/watch?v=w_2Pmy4f4Rs&t=4s)
- [Junio](https://www.youtube.com/watch?v=wzRXHcuc3fI&t=1458s)
- [Mayo](https://www.youtube.com/watch?v=rMUmB-iNyCA&t=7s) 

En cuanto al nivel de los participantes en su mayoría son personas que ya trabajan o han usado Angular anteriormente.

**Comment by gquinteros93** [comment]
@eduardoRoth te animas a pasarme tu email o escribirme a german.quinteros.1993@gmail.com ? 
Asi hoy previo a la meetup te comparto el link para hacer la prueba de sonido y video.
Gracias 👍

**Comment by eduardoRoth** [comment]
Hola @gquinteros93 , claro; mi email es **earoth88@gmail.com**

**Comment by gquinteros93** [comment]
Cierro ticket porque la charla fue dada en la meetup de Agosto de 2020.
[Link de la meetup](https://www.youtube.com/watch?v=Hgoq8sxBGSc)
