### ISSUE TITLE
Monorepo con Nx extensions

### ISSUE THREAD

**Issue by agusdutra** [AngularMVD/angularmvd#7]
* Agustín Dutra

https://github.com/nrwl/nx

(Esta la dejamos para después)

**Comment by NachoVazquez** [comment]
Estoy preparando un articulo sobre este tema. Cuando este listo, lo voy a convertir en una charla. Hay bastante contenido a cubrir así que no tiene que quedar en solo una charla, se puede hacer varias relacionadas.🦾

**Comment by guillermochimi** [comment]
Sera que te da para octubre?? :)

**Comment by NachoVazquez** [comment]
Para octubre puedo preparar una charla de introduccion a `Nx` pero no creo que el contenido del articulo este listo. 

El articulo quizas este para noviembre-diciembre por problemas personales de tiempo.

**Comment by matiasdelgado** [comment]
Nacho, esta buenísimo el tema también. Nunca tuvimos charla de NX así que vendría bárbaro una introducción! 

Te paso la url al slack de la comunidad por si no estás todavía: https://owu.herokuapp.com/
