### ISSUE TITLE
Angular Material

### ISSUE THREAD

**Issue by bradelev** [AngularMVD/angularmvd#9]
Es una introducción básica a la librería [Angular Material](https://material.angular.io), una introducción al `theming` y un ejemplo customizando una app.

* Braulio De Leon
* [Github.com/bradelev](https://github.com/bradelev)
* [Material Design website](https://material.io)
* [Angular Material website](https://material.angular.io)

**Comment by matiasdelgado** [comment]
Links a los [Slides](https://docs.google.com/presentation/d/1pZrq2FKI-AKVsDGluMUtc0MgQ_KSoEVj4TTp00Pr2h8/edit?usp=sharing) y [Repo](https://github.com/bradelev/custom-material)
